name: .NET

on:
  push:
    branches: [ master ]
  pull_request:    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.x
    - name: Build
      run: dotnet build src --configuration Release
